### ISSUE TITLE
Document cell type annotations

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-docs#130]
We will need to update both the processing information doc and the SCE contents documents to include information about the available cell type annotations.

**Comment by sjspielman** [comment]
Some details about what belongs here:

## SCE contents
> Noting some of was captured in #133, which I'm going to close in favor of collecting everything in this issue.

### If `SingleR` was run...

* `metadata` in the processed SCE:
  * `singler_results` is the full `SingleR` object
  * `reference_name` is the reference dataset name
  * `singler_reference_label` is the label type that was used in the reference (generally `label.ont`)
  * The `celltype_methods` vector will contain `"singler"`
* `colData` in the processed SCE:
  * `singler_celltype_annotation` are the annotated cell types, taken from pruned labels (so unclassified are `NA`)
  * `singler_celltype_ontology` is the ontology for the cell type. Only present if ontologies were used for cell typing in the first place

### If `CellAssign` was run...

* `metadata` in the processed SCE:
  * `cellassign_predictions` are matrix of all predictions; full result analogous to `singler_results`
  * `cellassign_reference` is the organ for which marker genes were obtained from PanglaoDB
  * The `celltype_methods` vector will contain `"cellassign"`
* `colData` in the processed SCE:
  * `cellassign_celltype_annotation` are the annotated cell types where unclassified are labeled as "other"
  * `cellassign_max_prediction` is the prediction score, which is a probability of the assigned celltype given the provided cell types

**Comment by sjspielman** [comment]
More details!

## `SingleR` implementation

- We identify a reference based on the tissue type of the given sample, generally using the `celldex` package. 
- We consider reference ontology labels when possible
- We save the `pruned.labels` to the colData

## `CellAssign` implementation

- We identify a set of marker genes using PanglaoDB; for given tissue type we use all genes associated with that organ
- We include an additional cell type "other" which has 0 expression of the marker genes so that cells which cannot be confidently annotated based on the set of marker genes end up getting annotated as "other"

**Comment by sjspielman** [comment]
Closed by #134
