### ISSUE TITLE
Add cell type annotation to getting started docs

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/scpca-docs#165]
Right now the getting started docs include information on how to access and work with the processed information we have in our objects (like PCA, UMAP, clusters, etc). We should include a section on cell type annotation. This should include both how to pull out the various cell types, how to find the associated references, and maybe some useful links on cell type annotation with SingleR/CellAssign. We probably also want to mention the supplemental cell type report and what type of information you can find there.

**Comment by sjspielman** [comment]
When requesting review here _from Jackie_, send her an object to test with!

**Comment by sjspielman** [comment]
While we're here, also double back to `sce_file_contents.md` to add these metadata fields:

https://github.com/AlexsLemonade/scpca-nf/issues/470#issuecomment-1802151588

**Comment by sjspielman** [comment]
> When requesting review here _from Jackie_, send her an object to test with!

**WOOPS.** 

@jaclyn-taroni, let's chat :grimacing:! The updated getting started instructions have been reviewed and merged, but we can go around again for you to have a look separately as someone not too in the weeds of developing the code. Since the PR where changes were made is closed, I could maybe revert the merge and open a new PR to go again? Do you think that is reasonable here? 

Here's the current version of the file: https://github.com/AlexsLemonade/scpca-docs/blob/325bfdbf150babcd360510a891d5ec786a68708d/docs/getting_started.md

Let me know what you think for the right next steps and I will Slack you some files!! Sorry about missing that!

**Comment by jaclyn-taroni** [comment]
It seems pretty reasonable. I will pick a nit, though – some of the publication references in the cell annotation section use `[]` instead of `()` and I don't know why.

**Comment by sjspielman** [comment]
Closed by #193 and #204
